now checks if task dir already exists

diff --git a/madgraph/bin/submit b/madgraph/bin/submit
--- a/madgraph/bin/submit
+++ b/madgraph/bin/submit
@@ -73,6 +73,11 @@ fi
 PROCESS=$(basename $CARDDIR)
 TASKDIR=$PWD/tasks/$PROCESS
 
+if [[ -d $TASKDIR ]]; then
+    echo "ERROR: $TASKDIR already exists; move or delete it and run again"
+    exit 1
+fi
+
 # Make package
 echo "Creating tarball for $PROCESS"
 mkdir -p workdir
